version: '2'
services:
    banking-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/banking/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=banking
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
